# Generated by Django 4.0.5 on 2022-06-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poststatus',
            options={'verbose_name_plural': 'Post Statuses'},
        ),
    ]
